const videos = [{
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/1.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/2.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/3.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/4.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/5.webp',
},
{
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/6.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/7.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/8.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/9.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/10.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/11.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/12.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/13.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/14.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/15.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/16.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/17.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/18.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/19.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/20.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/21.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/22.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/23.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/24.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/25.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/26.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/27.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/28.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/29.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/30.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/31.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/32.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/33.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/34.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/35.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/36.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/37.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/38.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/39.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/40.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/41.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/42.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/43.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/44.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/45.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/46.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/47.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/48.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/49.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/50.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/51.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/52.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/53.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/54.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/55.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/56.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/57.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/58.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/59.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/60.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/61.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/62.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/63.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/64.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/65.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/66.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/67.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/68.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/69.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/70.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/71.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/72.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/73.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/74.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/75.webp',
},
];

const clips = [{
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/1.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/2.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/3.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/4.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/5.webp',
},
{
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/6.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/7.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/8.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/9.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/10.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/11.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/12.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/13.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/14.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/15.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/16.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/17.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/18.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/19.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/20.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/21.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/22.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/23.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/24.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/25.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/26.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/27.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/28.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/29.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/30.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/31.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/32.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/33.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/34.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/35.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/36.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/37.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/38.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/39.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/40.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/41.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/42.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/43.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/44.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/45.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/46.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/47.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/48.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/49.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/50.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/51.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/52.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/53.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/54.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/55.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/56.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/57.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/58.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/59.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/60.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/61.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/62.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/63.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/64.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/65.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/66.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/67.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/68.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/69.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/70.webp',
}, {
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/71.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/72.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/73.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/74.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/75.webp',
},
];

module.exports.videos = videos;
module.exports.clips = clips;