const recentBroadcasts = [{
  video_id: 11,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Toys Handcrafted',
  description: 'Doloremque illum amet occaecati sequi ad.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/51.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/52.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/53.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/54.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/55.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '00:36:09',
  view_count: 296,
  created_at: 1
},
{
  video_id: 1,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Credit Card Account Bedfordshire',
  description: 'Consectetur asperiores ratione iste.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/1.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/2.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/3.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/4.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/5.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '15:05:45',
  view_count: 121,
  created_at: 3
},
{
  video_id: 6,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Jewelery auxiliary',
  description: 'Architecto est qui esse beatae.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/26.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/27.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/28.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/29.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/30.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '11:16:59',
  view_count: 362,
  created_at: 4
},
{
  video_id: 7,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Steel lavender',
  description: 'Autem ullam voluptatem eos et eligendi.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/31.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/32.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/33.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/34.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/35.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '06:00:29',
  view_count: 380,
  created_at: 5
},
{
  video_id: 9,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'FTP application',
  description: 'Vel enim suscipit modi aspernatur non qui quas non ullam.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/41.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/42.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/43.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/44.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/45.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '20:49:17',
  view_count: 54,
  created_at: 5
},
{
  video_id: 10,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Awesome Fresh Chicken maroon',
  description: 'Aut quae odit.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/46.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/47.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/48.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/49.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/50.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '13:48:21',
  view_count: 148,
  created_at: 6
},
{
  video_id: 3,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Mexican Peso Mexican Unidad de Inversion (UDI) Borders',
  description: 'Aut et autem animi provident neque ipsam.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/11.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/12.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/13.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/14.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/15.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '02:08:38',
  view_count: 346,
  created_at: 9
},
{
  video_id: 2,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'quantifying Planner',
  description: 'Sapiente eum voluptas praesentium atque voluptatem reprehenderit qui.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/6.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/7.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/8.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/9.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/10.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '10:13:57',
  view_count: 206,
  created_at: 9
}];

const recentHighlights = [{
  video_id: 8,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Money Market Account driver',
  description: 'Voluptas eveniet id ipsam.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/36.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/37.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/38.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/39.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/40.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '13:45:58',
  view_count: 381,
  created_at: 12
},
{
  video_id: 7,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Steel lavender',
  description: 'Autem ullam voluptatem eos et eligendi.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/31.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/32.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/33.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/34.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/35.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '06:00:29',
  view_count: 380,
  created_at: 5
},
{
  video_id: 6,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Jewelery auxiliary',
  description: 'Architecto est qui esse beatae.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/26.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/27.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/28.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/29.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/30.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '11:16:59',
  view_count: 362,
  created_at: 4
},
{
  video_id: 5,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'parsing Australian Dollar',
  description: 'Praesentium provident molestiae rerum quae quidem dolorum.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/21.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/22.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/23.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/24.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/25.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '20:31:29',
  view_count: 359,
  created_at: 11
},
{
  video_id: 3,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Mexican Peso Mexican Unidad de Inversion (UDI) Borders',
  description: 'Aut et autem animi provident neque ipsam.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/11.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/12.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/13.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/14.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/15.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '02:08:38',
  view_count: 346,
  created_at: 9
},
{
  video_id: 11,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Toys Handcrafted',
  description: 'Doloremque illum amet occaecati sequi ad.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/51.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/52.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/53.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/54.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/55.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '00:36:09',
  view_count: 296,
  created_at: 1
},
{
  video_id: 13,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'Auto Loan Account payment',
  description: 'Repudiandae mollitia harum esse earum enim consectetur quis.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/61.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/62.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/63.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/64.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/65.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '15:55:42',
  view_count: 210,
  created_at: 11
},
{
  video_id: 2,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'quantifying Planner',
  description: 'Sapiente eum voluptas praesentium atque voluptatem reprehenderit qui.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/6.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/7.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/8.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/9.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/10.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '10:13:57',
  view_count: 206,
  created_at: 9
}];

const popularClips = [{
  clip_id: 6,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'compressing magenta',
  description: 'Reiciendis est quae.',
  clipped_by: 'Jennings_Spinka55',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/26.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/27.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/28.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/29.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/30.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '17:22:42',
  view_count: 393,
  created_at: 6
},
{
  clip_id: 1,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'parse hack',
  description: 'Deserunt possimus laudantium iste occaecati.',
  clipped_by: 'Rashawn2',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/1.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/2.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/3.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/4.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/5.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '17:58:28',
  view_count: 355,
  created_at: 10
},
{
  clip_id: 4,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'leading-edge European Unit of Account 17(E.U.A.-17)',
  description: 'Aut dolores iusto et et quibusdam et sed provident.',
  clipped_by: 'Lucas.Frami47',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/16.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/17.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/18.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/19.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/20.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '18:05:09',
  view_count: 328,
  created_at: 4
},
{
  clip_id: 12,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'IB parsing',
  description: 'Nemo earum aspernatur vitae impedit quo cumque aut est.',
  clipped_by: 'Ollie66',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/56.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/57.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/58.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/59.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/60.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '18:20:03',
  view_count: 303,
  created_at: 7
},
{
  clip_id: 11,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Engineer CFA Franc BEAC',
  description: 'Quia quia optio repellendus odio recusandae voluptatem earum natus placeat.',
  clipped_by: 'Kristina_Bashirian',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/51.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/52.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/53.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/54.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/55.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '20:19:29',
  view_count: 298,
  created_at: 3
},
{
  clip_id: 15,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'Wooden Balanced',
  description: 'Aspernatur velit reprehenderit vero non eius saepe.',
  clipped_by: 'Jada_OHara30',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/71.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/72.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/73.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/74.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/75.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '08:54:50',
  view_count: 280,
  created_at: 1
},
{
  clip_id: 5,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'PCI Pizza',
  description: 'Voluptatem optio possimus vel voluptatem illum reprehenderit.',
  clipped_by: 'Magnus69',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/21.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/22.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/23.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/24.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/25.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '11:55:29',
  view_count: 280,
  created_at: 7
},
{
  clip_id: 3,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'back-end Georgia',
  description: 'Est ratione vero culpa et totam.',
  clipped_by: 'Noemie_Quitzon',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/11.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/12.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/13.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/14.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/15.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '08:23:10',
  view_count: 261,
  created_at: 11
}];

const allVideos = [{
  video_id: 1,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Credit Card Account Bedfordshire',
  description: 'Consectetur asperiores ratione iste.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/1.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/2.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/3.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/4.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/5.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '15:05:45',
  view_count: 121,
  created_at: 3
},
{
  video_id: 2,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'quantifying Planner',
  description: 'Sapiente eum voluptas praesentium atque voluptatem reprehenderit qui.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/6.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/7.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/8.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/9.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/10.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '10:13:57',
  view_count: 206,
  created_at: 9
},
{
  video_id: 3,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Mexican Peso Mexican Unidad de Inversion (UDI) Borders',
  description: 'Aut et autem animi provident neque ipsam.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/11.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/12.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/13.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/14.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/15.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '02:08:38',
  view_count: 346,
  created_at: 9
},
{
  video_id: 4,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'US Dollar Investment Account',
  description: 'Iusto quis ipsum magni ut ratione molestiae et.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/16.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/17.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/18.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/19.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/20.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '11:39:40',
  view_count: 95,
  created_at: 11
},
{
  video_id: 5,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'parsing Australian Dollar',
  description: 'Praesentium provident molestiae rerum quae quidem dolorum.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/21.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/22.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/23.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/24.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/25.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '20:31:29',
  view_count: 359,
  created_at: 11
},
{
  video_id: 6,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Jewelery auxiliary',
  description: 'Architecto est qui esse beatae.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/26.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/27.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/28.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/29.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/30.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '11:16:59',
  view_count: 362,
  created_at: 4
},
{
  video_id: 7,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Steel lavender',
  description: 'Autem ullam voluptatem eos et eligendi.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/31.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/32.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/33.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/34.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/35.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '06:00:29',
  view_count: 380,
  created_at: 5
},
{
  video_id: 8,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Money Market Account driver',
  description: 'Voluptas eveniet id ipsam.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/36.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/37.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/38.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/39.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/40.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '13:45:58',
  view_count: 381,
  created_at: 12
},
{
  video_id: 9,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'FTP application',
  description: 'Vel enim suscipit modi aspernatur non qui quas non ullam.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/41.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/42.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/43.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/44.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/45.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '20:49:17',
  view_count: 54,
  created_at: 5
},
{
  video_id: 10,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Awesome Fresh Chicken maroon',
  description: 'Aut quae odit.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/46.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/47.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/48.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/49.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/50.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '13:48:21',
  view_count: 148,
  created_at: 6
},
{
  video_id: 11,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Toys Handcrafted',
  description: 'Doloremque illum amet occaecati sequi ad.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/51.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/52.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/53.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/54.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/55.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '00:36:09',
  view_count: 296,
  created_at: 1
},
{
  video_id: 12,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Pass Alabama',
  description: 'Labore labore quisquam sapiente placeat odio ut repudiandae.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/56.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/57.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/58.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/59.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/60.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '00:34:41',
  view_count: 137,
  created_at: 11
},
{
  video_id: 13,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'Auto Loan Account payment',
  description: 'Repudiandae mollitia harum esse earum enim consectetur quis.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/61.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/62.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/63.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/64.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/65.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '15:55:42',
  view_count: 210,
  created_at: 11
},
{
  video_id: 14,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'PCI driver',
  description: 'Non natus ut nesciunt rerum quae quis et qui rerum.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/66.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/67.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/68.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/69.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/70.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '09:51:03',
  view_count: 157,
  created_at: 12
},
{
  video_id: 15,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'Small Borders',
  description: 'Qui sed voluptatem voluptatem aliquam ducimus quis.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/71.webp',
  thumbnail_url_2: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/72.webp',
  thumbnail_url_3: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/73.webp',
  thumbnail_url_4: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/74.webp',
  thumbnail_url_5: 'https://s3-us-west-1.amazonaws.com/gamestillswebp/75.webp',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '08:43:55',
  view_count: 40,
  created_at: 10
}];


module.exports.recentBroadcasts = recentBroadcasts;
module.exports.recentHighlights = recentHighlights;
module.exports.popularClips = popularClips;
module.exports.allVideos = allVideos;