const videos = [{
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://vignette.wikia.nocookie.net/darksouls/images/e/e9/Dark-souls-ii-gameplay-screenshot-06.jpg/revision/latest/scale-to-width-down/640?cb=20130410233236',
  thumbnail_url_2: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/dlc2_17.jpg',
  thumbnail_url_3: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/dlc2_20.jpg',
  thumbnail_url_4: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/gthumbnails/dlc2_18.jpg',
  thumbnail_url_5: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/gthumbnails/dlc2_16.jpg',
  },
  {
    user_name: 'A_Seagull',
    game_name: 'Dark Souls III',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
    thumbnail_url_1: 'https://fextralife.com/wp-content/uploads/2015/08/Pursuer2_sample_darksouls3-300x169.jpg',
    thumbnail_url_2: 'https://fextralife.com/wp-content/uploads/2015/08/Pursuer1_sample_darksouls3-300x169.jpg',
    thumbnail_url_3: 'https://fextralife.com/wp-content/uploads/2015/08/ArmoredBeast_sample_darksouls3-300x169.jpg',
    thumbnail_url_4: 'https://fextralife.com/wp-content/uploads/2015/08/Undead_sample_darksouls3-300x169.jpg',
    thumbnail_url_5: 'https://fextralife.com/wp-content/uploads/2015/08/ReadyStanceArt_sample_darksouls3-300x169.jpg',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Dark Souls III',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
    thumbnail_url_1: 'https://fextralife.com/wp-content/uploads/2015/08/RollingShot_sample_darksouls3-300x169.jpg',
    thumbnail_url_2: 'https://fextralife.com/wp-content/uploads/2015/08/SpinArt_sample_darksouls3-300x169.jpg',
    thumbnail_url_3: 'https://fextralife.com/wp-content/uploads/2015/08/Warcry_sample_darksouls3-300x169.jpg',
    thumbnail_url_4: 'https://fextralife.com/wp-content/uploads/2015/08/LungeArt_sample_darksouls3-300x169.jpg',
    thumbnail_url_5: 'https://fextralife.com/wp-content/uploads/2015/08/DarkKnight_sample_darksouls3-300x177.jpg',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Dark Souls III',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
    thumbnail_url_1: 'https://i.imgur.com/0RUxXTx.jpg?1',
    thumbnail_url_2: 'https://i.imgur.com/Dr0EgRv.jpg?1',
    thumbnail_url_3: 'https://i.imgur.com/KEouADT.jpg?1',
    thumbnail_url_4: 'https://i.imgur.com/tuWxihm.jpg?1',
    thumbnail_url_5: 'https://i.imgur.com/ukme2eO.jpg?1',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Dark Souls III',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
    thumbnail_url_1: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_001.jpg',
    thumbnail_url_2: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_003.jpg',
    thumbnail_url_3: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_005.jpg',
    thumbnail_url_4: 'https://i.imgur.com/WDveXJx.jpg?1',
    thumbnail_url_5: 'https://i.imgur.com/umlD9tO.jpg?1',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Dark Souls III',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
    thumbnail_url_1: 'https://i.imgur.com/Kb0ogF3.jpg?1',
    thumbnail_url_2: 'https://i.imgur.com/0zKL2Ov.jpg?1',
    thumbnail_url_3: 'https://i.imgur.com/QXps7wM.jpg?1',
    thumbnail_url_4: 'https://i.imgur.com/yQBzHki.jpg?1',
    thumbnail_url_5: 'https://i.imgur.com/1VExacK.jpg?1',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Dark Souls III',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
    thumbnail_url_1: 'https://i.imgur.com/MidKpcy.jpg?1',
    thumbnail_url_2: 'https://i.imgur.com/xpWmJAf.jpg?1',
    thumbnail_url_3: 'https://i.imgur.com/Bb5FQ9d.jpg?1',
    thumbnail_url_4: 'https://i.imgur.com/KqHwWIj.jpg?1',
    thumbnail_url_5: 'https://i.imgur.com/K4Q8niX.jpg?1',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Overwatch',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
    thumbnail_url_1: 'https://i.imgur.com/I6yM8uM.png',
    thumbnail_url_2: 'https://i.imgur.com/NqXbLZj.png',
    thumbnail_url_3: 'https://i.imgur.com/SUS5P9i.png',
    thumbnail_url_4: 'https://i.imgur.com/cWQ8tGR.png',
    thumbnail_url_5: 'https://i.imgur.com/SPV2v29.jpg',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Overwatch',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
    thumbnail_url_1: 'https://i.imgur.com/2E0RsZz.jpg',
    thumbnail_url_2: 'https://i.imgur.com/ibDLj60.jpg',
    thumbnail_url_3: 'https://i.imgur.com/wEBv9tt.jpg',
    thumbnail_url_4: 'https://i.imgur.com/sR4KYI9.png',
    thumbnail_url_5: 'https://i.imgur.com/nk0Uoys.png',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Overwatch',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
    thumbnail_url_1: 'https://i.imgur.com/UHVZeYx.png',
    thumbnail_url_2: 'https://i.imgur.com/NW90sLx.png',
    thumbnail_url_3: 'https://i.imgur.com/gnStqOa.png',
    thumbnail_url_4: 'https://i.imgur.com/2lRWk4P.png',
    thumbnail_url_5: 'https://i.imgur.com/6rf7s6R.png',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Overwatch',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
    thumbnail_url_1: 'https://i.imgur.com/dFqpmMv.png',
    thumbnail_url_2: 'https://i.imgur.com/vlaTV53.png',
    thumbnail_url_3: 'https://i.imgur.com/oP5VeGD.png',
    thumbnail_url_4: 'https://i.imgur.com/daPof5D.png',
    thumbnail_url_5: 'https://i.imgur.com/hrxibQx.png',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Overwatch',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
    thumbnail_url_1: 'https://i.imgur.com/Q1ASTgq.jpg',
    thumbnail_url_2: 'https://i.imgur.com/rZ3w4JB.jpg',
    thumbnail_url_3: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745603l.jpg',
    thumbnail_url_4: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745758l.jpg',
    thumbnail_url_5: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745108l.jpg',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Subnautica',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
    thumbnail_url_1: 'https://i.imgur.com/vRFeaU3.jpg',
    thumbnail_url_2: 'https://i.imgur.com/ZCQMSXJ.jpg',
    thumbnail_url_3: 'https://i.imgur.com/Cwurrst.jpg',
    thumbnail_url_4: 'https://i.imgur.com/GeHP2x6.jpg',
    thumbnail_url_5: 'https://i.imgur.com/mvlPYV4.jpg',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Subnautica',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
    thumbnail_url_1: 'https://i.imgur.com/AjgdzRk.jpg',
    thumbnail_url_2: 'https://i.imgur.com/xGugOtM.jpg',
    thumbnail_url_3: 'https://i.imgur.com/mElLQY5.jpg',
    thumbnail_url_4: 'https://i.imgur.com/cvEeZiY.jpg',
    thumbnail_url_5: 'https://i.imgur.com/FJCrf9w.jpg',
  }, {
    user_name: 'A_Seagull',
    game_name: 'Subnautica',
    game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
    thumbnail_url_1: 'https://envul.com/ius/screenshots/subnautica/subnautica-wallpaper-2.png',
    thumbnail_url_2: 'https://envul.com/ius/screenshots/subnautica/subnautica-art-14.png',
    thumbnail_url_3: 'https://envul.com/ius/screenshots/subnautica/subnautica-poster-22.png',
    thumbnail_url_4: 'https://envul.com/ius/screenshots/subnautica/subnautica-gameplay-6.png',
    thumbnail_url_5: 'https://i.imgur.com/xEMchXo.jpg',
  },
];

const clips = [{
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://vignette.wikia.nocookie.net/darksouls/images/e/e9/Dark-souls-ii-gameplay-screenshot-06.jpg/revision/latest/scale-to-width-down/640?cb=20130410233236',
  thumbnail_url_2: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/dlc2_17.jpg',
  thumbnail_url_3: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/dlc2_20.jpg',
  thumbnail_url_4: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/gthumbnails/dlc2_18.jpg',
  thumbnail_url_5: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/gthumbnails/dlc2_16.jpg',
},
{
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://fextralife.com/wp-content/uploads/2015/08/Pursuer2_sample_darksouls3-300x169.jpg',
  thumbnail_url_2: 'https://fextralife.com/wp-content/uploads/2015/08/Pursuer1_sample_darksouls3-300x169.jpg',
  thumbnail_url_3: 'https://fextralife.com/wp-content/uploads/2015/08/ArmoredBeast_sample_darksouls3-300x169.jpg',
  thumbnail_url_4: 'https://fextralife.com/wp-content/uploads/2015/08/Undead_sample_darksouls3-300x169.jpg',
  thumbnail_url_5: 'https://fextralife.com/wp-content/uploads/2015/08/ReadyStanceArt_sample_darksouls3-300x169.jpg',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://fextralife.com/wp-content/uploads/2015/08/RollingShot_sample_darksouls3-300x169.jpg',
  thumbnail_url_2: 'https://fextralife.com/wp-content/uploads/2015/08/SpinArt_sample_darksouls3-300x169.jpg',
  thumbnail_url_3: 'https://fextralife.com/wp-content/uploads/2015/08/Warcry_sample_darksouls3-300x169.jpg',
  thumbnail_url_4: 'https://fextralife.com/wp-content/uploads/2015/08/LungeArt_sample_darksouls3-300x169.jpg',
  thumbnail_url_5: 'https://fextralife.com/wp-content/uploads/2015/08/DarkKnight_sample_darksouls3-300x177.jpg',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://i.imgur.com/0RUxXTx.jpg?1',
  thumbnail_url_2: 'https://i.imgur.com/Dr0EgRv.jpg?1',
  thumbnail_url_3: 'https://i.imgur.com/KEouADT.jpg?1',
  thumbnail_url_4: 'https://i.imgur.com/tuWxihm.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/ukme2eO.jpg?1',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_001.jpg',
  thumbnail_url_2: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_003.jpg',
  thumbnail_url_3: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_005.jpg',
  thumbnail_url_4: 'https://i.imgur.com/WDveXJx.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/umlD9tO.jpg?1',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://i.imgur.com/Kb0ogF3.jpg?1',
  thumbnail_url_2: 'https://i.imgur.com/0zKL2Ov.jpg?1',
  thumbnail_url_3: 'https://i.imgur.com/QXps7wM.jpg?1',
  thumbnail_url_4: 'https://i.imgur.com/yQBzHki.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/1VExacK.jpg?1',
}, {
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  thumbnail_url_1: 'https://i.imgur.com/MidKpcy.jpg?1',
  thumbnail_url_2: 'https://i.imgur.com/xpWmJAf.jpg?1',
  thumbnail_url_3: 'https://i.imgur.com/Bb5FQ9d.jpg?1',
  thumbnail_url_4: 'https://i.imgur.com/KqHwWIj.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/K4Q8niX.jpg?1',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://i.imgur.com/I6yM8uM.png',
  thumbnail_url_2: 'https://i.imgur.com/NqXbLZj.png',
  thumbnail_url_3: 'https://i.imgur.com/SUS5P9i.png',
  thumbnail_url_4: 'https://i.imgur.com/cWQ8tGR.png',
  thumbnail_url_5: 'https://i.imgur.com/SPV2v29.jpg',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://i.imgur.com/2E0RsZz.jpg',
  thumbnail_url_2: 'https://i.imgur.com/ibDLj60.jpg',
  thumbnail_url_3: 'https://i.imgur.com/wEBv9tt.jpg',
  thumbnail_url_4: 'https://i.imgur.com/sR4KYI9.png',
  thumbnail_url_5: 'https://i.imgur.com/nk0Uoys.png',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://i.imgur.com/UHVZeYx.png',
  thumbnail_url_2: 'https://i.imgur.com/NW90sLx.png',
  thumbnail_url_3: 'https://i.imgur.com/gnStqOa.png',
  thumbnail_url_4: 'https://i.imgur.com/2lRWk4P.png',
  thumbnail_url_5: 'https://i.imgur.com/6rf7s6R.png',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://i.imgur.com/dFqpmMv.png',
  thumbnail_url_2: 'https://i.imgur.com/vlaTV53.png',
  thumbnail_url_3: 'https://i.imgur.com/oP5VeGD.png',
  thumbnail_url_4: 'https://i.imgur.com/daPof5D.png',
  thumbnail_url_5: 'https://i.imgur.com/hrxibQx.png',
}, {
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  thumbnail_url_1: 'https://i.imgur.com/Q1ASTgq.jpg',
  thumbnail_url_2: 'https://i.imgur.com/rZ3w4JB.jpg',
  thumbnail_url_3: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745603l.jpg',
  thumbnail_url_4: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745758l.jpg',
  thumbnail_url_5: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745108l.jpg',
}, {
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  thumbnail_url_1: 'https://i.imgur.com/vRFeaU3.jpg',
  thumbnail_url_2: 'https://i.imgur.com/ZCQMSXJ.jpg',
  thumbnail_url_3: 'https://i.imgur.com/Cwurrst.jpg',
  thumbnail_url_4: 'https://i.imgur.com/GeHP2x6.jpg',
  thumbnail_url_5: 'https://i.imgur.com/mvlPYV4.jpg',
}, {
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  thumbnail_url_1: 'https://i.imgur.com/AjgdzRk.jpg',
  thumbnail_url_2: 'https://i.imgur.com/xGugOtM.jpg',
  thumbnail_url_3: 'https://i.imgur.com/mElLQY5.jpg',
  thumbnail_url_4: 'https://i.imgur.com/cvEeZiY.jpg',
  thumbnail_url_5: 'https://i.imgur.com/FJCrf9w.jpg',
}, {
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  thumbnail_url_1: 'https://envul.com/ius/screenshots/subnautica/subnautica-wallpaper-2.png',
  thumbnail_url_2: 'https://envul.com/ius/screenshots/subnautica/subnautica-art-14.png',
  thumbnail_url_3: 'https://envul.com/ius/screenshots/subnautica/subnautica-poster-22.png',
  thumbnail_url_4: 'https://envul.com/ius/screenshots/subnautica/subnautica-gameplay-6.png',
  thumbnail_url_5: 'https://i.imgur.com/xEMchXo.jpg',
},
];


module.exports.videos = videos;
module.exports.clips = clips;