const recentBroadcasts = [{
  video_id: 7,
  user_name: 'Jayde74',
  game_name: 'reboot hard drive',
  game_box_art_url: 'http://lorempixel.com/640/480/sports',
  title: 'Central withdrawal',
  description: 'Nostrum occaecati omnis maiores velit magni aut in accusantium perspiciatis.',
  url: 'http://teresa.com',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '08:54:04',
  view_count: 84986,
  created_at: 2,
  streamer_id: 1,
  game_id: 7
},
{
  video_id: 12,
  user_name: 'Rossie67',
  game_name: 'reboot hard drive',
  game_box_art_url: 'http://lorempixel.com/640/480/city',
  title: 'budgetary management Sleek',
  description: 'Hic accusamus eligendi voluptatem et ducimus.',
  url: 'https://vincenzo.com',
  thumbnail_url: 'http://lorempixel.com/640/480/nature',
  duration: '11:32:55',
  view_count: 13623,
  created_at: 2,
  streamer_id: 1,
  game_id: 12
},
{
  video_id: 35,
  user_name: 'Garrick.Johnson62',
  game_name: 'quantify microchip',
  game_box_art_url: 'http://lorempixel.com/640/480/business',
  title: 'IB mindshare',
  description: 'Quibusdam accusantium quia delectus.',
  url: 'https://henry.org',
  thumbnail_url: 'http://lorempixel.com/640/480/nature',
  duration: '17:40:31',
  view_count: 60355,
  created_at: 5,
  streamer_id: 1,
  game_id: 35
},
{
  video_id: 58,
  user_name: 'Noble96',
  game_name: 'reboot sensor',
  game_box_art_url: 'http://lorempixel.com/640/480/nightlife',
  title: 'Games Avon',
  description: 'Harum nulla vitae.',
  url: 'http://bradford.org',
  thumbnail_url: 'http://lorempixel.com/640/480/animals',
  duration: '19:57:55',
  view_count: 50247,
  created_at: 6,
  streamer_id: 1,
  game_id: 58
},
{
  video_id: 43,
  user_name: 'Mertie48',
  game_name: 'copy capacitor',
  game_box_art_url: 'http://lorempixel.com/640/480/sports',
  title: 'back up e-tailers',
  description: 'Esse esse facilis quas delectus et.',
  url: 'https://janie.info',
  thumbnail_url: 'http://lorempixel.com/640/480/abstract',
  duration: '18:44:59',
  view_count: 64008,
  created_at: 7,
  streamer_id: 1,
  game_id: 43
},
{
  video_id: 4,
  user_name: 'Russ0',
  game_name: 'reboot feed',
  game_box_art_url: 'http://lorempixel.com/640/480/nature',
  title: 'feed Handmade',
  description: 'Quod quia voluptatem qui nulla sed.',
  url: 'http://delpha.net',
  thumbnail_url: 'http://lorempixel.com/640/480/abstract',
  duration: '15:06:15',
  view_count: 17489,
  created_at: 7,
  streamer_id: 1,
  game_id: 4
},
{
  video_id: 57,
  user_name: 'Jettie_Schaden',
  game_name: 'navigate circuit',
  game_box_art_url: 'http://lorempixel.com/640/480/food',
  title: 'bi-directional navigating',
  description: 'Quisquam sit unde maiores.',
  url: 'https://tyrell.com',
  thumbnail_url: 'http://lorempixel.com/640/480/business',
  duration: '19:17:26',
  view_count: 12813,
  created_at: 9,
  streamer_id: 1,
  game_id: 57
},
{
  video_id: 5,
  user_name: 'Elsa43',
  game_name: 'back up port',
  game_box_art_url: 'http://lorempixel.com/640/480/nightlife',
  title: 'Tools Rustic Metal Bike',
  description: 'Temporibus sed quibusdam dolorem enim repellendus eius in.',
  url: 'https://terrell.name',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '03:21:18',
  view_count: 81106,
  created_at: 9,
  streamer_id: 1,
  game_id: 5
},
{
  video_id: 63,
  user_name: 'Doyle65',
  game_name: 'input array',
  game_box_art_url: 'http://lorempixel.com/640/480/sports',
  title: 'Montserrat Engineer',
  description: 'Omnis enim nemo.',
  url: 'http://isobel.net',
  thumbnail_url: 'http://lorempixel.com/640/480/food',
  duration: '04:18:10',
  view_count: 40342,
  created_at: 11,
  streamer_id: 1,
  game_id: 63
},
{
  video_id: 99,
  user_name: 'Leon72',
  game_name: 'parse firewall',
  game_box_art_url: 'http://lorempixel.com/640/480/city',
  title: 'Investment Account maroon',
  description: 'Ea omnis eum sit et placeat blanditiis.',
  url: 'https://nelson.org',
  thumbnail_url: 'http://lorempixel.com/640/480/city',
  duration: '03:15:10',
  view_count: 32682,
  created_at: 11,
  streamer_id: 1,
  game_id: 99
},
{
  video_id: 9,
  user_name: 'Justyn25',
  game_name: 'generate bandwidth',
  game_box_art_url: 'http://lorempixel.com/640/480/technics',
  title: 'Checking Account overriding',
  description: 'Qui ut expedita et.',
  url: 'https://aniya.info',
  thumbnail_url: 'http://lorempixel.com/640/480/people',
  duration: '14:42:34',
  view_count: 5093,
  created_at: 13,
  streamer_id: 1,
  game_id: 9
},
{
  video_id: 26,
  user_name: 'Opal.White',
  game_name: 'back up hard drive',
  game_box_art_url: 'http://lorempixel.com/640/480/people',
  title: 'interactive Cambridgeshire',
  description: 'Qui facere incidunt.',
  url: 'http://lyla.org',
  thumbnail_url: 'http://lorempixel.com/640/480/abstract',
  duration: '02:59:52',
  view_count: 82458,
  created_at: 17,
  streamer_id: 1,
  game_id: 26
},
{
  video_id: 68,
  user_name: 'Mae54',
  game_name: 'quantify capacitor',
  game_box_art_url: 'http://lorempixel.com/640/480/city',
  title: 'indexing mint green',
  description: 'Nostrum ex dolorum aliquid quo praesentium molestiae.',
  url: 'https://darrel.com',
  thumbnail_url: 'http://lorempixel.com/640/480/people',
  duration: '16:29:14',
  view_count: 29684,
  created_at: 18,
  streamer_id: 1,
  game_id: 68
},
{
  video_id: 49,
  user_name: 'Rogers_Spinka',
  game_name: 'input pixel',
  game_box_art_url: 'http://lorempixel.com/640/480/transport',
  title: 'pink Officer',
  description: 'Rerum neque repellendus vitae id sit dolorem fugit molestias.',
  url: 'https://bell.org',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '14:50:58',
  view_count: 71409,
  created_at: 20,
  streamer_id: 1,
  game_id: 49
},
{
  video_id: 75,
  user_name: 'Ahmad.Harber54',
  game_name: 'reboot array',
  game_box_art_url: 'http://lorempixel.com/640/480/food',
  title: 'Specialist Internal',
  description: 'A qui aperiam labore quas impedit.',
  url: 'http://jena.biz',
  thumbnail_url: 'http://lorempixel.com/640/480/sports',
  duration: '18:54:56',
  view_count: 27100,
  created_at: 22,
  streamer_id: 1,
  game_id: 75
}]
const recentHighlights = [{
  video_id: 90,
  user_name: 'Eriberto_Marks74',
  game_name: 'generate transmitter',
  game_box_art_url: 'http://lorempixel.com/640/480/abstract',
  title: 'capacitor encompassing',
  description: 'Aut eum ipsa qui fugiat.',
  url: 'http://lukas.name',
  thumbnail_url: 'http://lorempixel.com/640/480/business',
  duration: '12:40:15',
  view_count: 97460,
  created_at: 42,
  streamer_id: 1,
  game_id: 90
},
{
  video_id: 2,
  user_name: 'Lennie89',
  game_name: 'input hard drive',
  game_box_art_url: 'http://lorempixel.com/640/480/transport',
  title: 'SQL Avon',
  description: 'Eum quia voluptatum.',
  url: 'http://jordy.info',
  thumbnail_url: 'http://lorempixel.com/640/480/transport',
  duration: '10:17:33',
  view_count: 97239,
  created_at: 52,
  streamer_id: 1,
  game_id: 2
},
{
  video_id: 6,
  user_name: 'Jamel78',
  game_name: 'index microchip',
  game_box_art_url: 'http://lorempixel.com/640/480/people',
  title: 'Bedfordshire Direct',
  description: 'Velit maxime ut quisquam libero dolor adipisci sit consequuntur tenetur.',
  url: 'http://sasha.com',
  thumbnail_url: 'http://lorempixel.com/640/480/city',
  duration: '23:06:56',
  view_count: 89845,
  created_at: 54,
  streamer_id: 1,
  game_id: 6
},
{
  video_id: 47,
  user_name: 'Allan_Wyman',
  game_name: 'connect array',
  game_box_art_url: 'http://lorempixel.com/640/480/nature',
  title: 'Incredible Fresh Salad Garden',
  description: 'Enim quis animi repellendus omnis iusto id qui officiis.',
  url: 'https://warren.name',
  thumbnail_url: 'http://lorempixel.com/640/480/nightlife',
  duration: '01:59:35',
  view_count: 87051,
  created_at: 51,
  streamer_id: 1,
  game_id: 47
},
{
  video_id: 19,
  user_name: 'Ola_Lesch75',
  game_name: 'hack monitor',
  game_box_art_url: 'http://lorempixel.com/640/480/animals',
  title: 'Tennessee South Africa',
  description: 'Ullam modi omnis illum sapiente culpa earum inventore saepe blanditiis.',
  url: 'https://brianne.org',
  thumbnail_url: 'http://lorempixel.com/640/480/abstract',
  duration: '07:27:45',
  view_count: 85005,
  created_at: 34,
  streamer_id: 1,
  game_id: 19
},
{
  video_id: 7,
  user_name: 'Jayde74',
  game_name: 'reboot hard drive',
  game_box_art_url: 'http://lorempixel.com/640/480/sports',
  title: 'Central withdrawal',
  description: 'Nostrum occaecati omnis maiores velit magni aut in accusantium perspiciatis.',
  url: 'http://teresa.com',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '08:54:04',
  view_count: 84986,
  created_at: 2,
  streamer_id: 1,
  game_id: 7
},
{
  video_id: 26,
  user_name: 'Opal.White',
  game_name: 'back up hard drive',
  game_box_art_url: 'http://lorempixel.com/640/480/people',
  title: 'interactive Cambridgeshire',
  description: 'Qui facere incidunt.',
  url: 'http://lyla.org',
  thumbnail_url: 'http://lorempixel.com/640/480/abstract',
  duration: '02:59:52',
  view_count: 82458,
  created_at: 17,
  streamer_id: 1,
  game_id: 26
},
{
  video_id: 5,
  user_name: 'Elsa43',
  game_name: 'back up port',
  game_box_art_url: 'http://lorempixel.com/640/480/nightlife',
  title: 'Tools Rustic Metal Bike',
  description: 'Temporibus sed quibusdam dolorem enim repellendus eius in.',
  url: 'https://terrell.name',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '03:21:18',
  view_count: 81106,
  created_at: 9,
  streamer_id: 1,
  game_id: 5
},
{
  video_id: 62,
  user_name: 'Malinda1',
  game_name: 'input panel',
  game_box_art_url: 'http://lorempixel.com/640/480/transport',
  title: 'feed calculate',
  description: 'Eaque porro quo omnis modi et quae.',
  url: 'http://stanford.biz',
  thumbnail_url: 'http://lorempixel.com/640/480/cats',
  duration: '22:35:54',
  view_count: 80067,
  created_at: 50,
  streamer_id: 1,
  game_id: 62
},
{
  video_id: 49,
  user_name: 'Rogers_Spinka',
  game_name: 'input pixel',
  game_box_art_url: 'http://lorempixel.com/640/480/transport',
  title: 'pink Officer',
  description: 'Rerum neque repellendus vitae id sit dolorem fugit molestias.',
  url: 'https://bell.org',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '14:50:58',
  view_count: 71409,
  created_at: 20,
  streamer_id: 1,
  game_id: 49
},
{
  video_id: 27,
  user_name: 'Cynthia.Mertz55',
  game_name: 'override system',
  game_box_art_url: 'http://lorempixel.com/640/480/city',
  title: 'Cheese District',
  description: 'Ut quia repudiandae saepe libero soluta minus sequi.',
  url: 'https://brigitte.com',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '12:41:10',
  view_count: 71240,
  created_at: 33,
  streamer_id: 1,
  game_id: 27
},
{
  video_id: 22,
  user_name: 'Cheyenne.Murray',
  game_name: 'navigate sensor',
  game_box_art_url: 'http://lorempixel.com/640/480/fashion',
  title: 'JBOD Kwanza',
  description: 'Blanditiis consequatur aspernatur doloribus aut fugiat beatae est soluta.',
  url: 'http://elda.biz',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '00:19:51',
  view_count: 69760,
  created_at: 29,
  streamer_id: 1,
  game_id: 22
},
{
  video_id: 41,
  user_name: 'Shane28',
  game_name: 'calculate sensor',
  game_box_art_url: 'http://lorempixel.com/640/480/animals',
  title: 'invoice XML',
  description: 'Molestias consectetur accusamus molestiae.',
  url: 'http://susie.org',
  thumbnail_url: 'http://lorempixel.com/640/480/nature',
  duration: '10:07:09',
  view_count: 67787,
  created_at: 41,
  streamer_id: 1,
  game_id: 41
},
{
  video_id: 17,
  user_name: 'Silas31',
  game_name: 'index port',
  game_box_art_url: 'http://lorempixel.com/640/480/food',
  title: 'Libyan Dinar cultivate',
  description: 'Optio voluptatibus sit et commodi aspernatur maiores ipsam.',
  url: 'https://julianne.net',
  thumbnail_url: 'http://lorempixel.com/640/480/abstract',
  duration: '09:34:46',
  view_count: 65868,
  created_at: 35,
  streamer_id: 1,
  game_id: 17
},
{
  video_id: 73,
  user_name: 'Theodore_Prohaska',
  game_name: 'copy feed',
  game_box_art_url: 'http://lorempixel.com/640/480/animals',
  title: 'partnerships Bedfordshire',
  description: 'Expedita quibusdam autem consectetur voluptas optio.',
  url: 'http://nigel.org',
  thumbnail_url: 'http://lorempixel.com/640/480/fashion',
  duration: '05:54:30',
  view_count: 64694,
  created_at: 27,
  streamer_id: 1,
  game_id: 73
}]
const popularClips = [{
  clip_id: 36,
  user_name: 'Carmel7',
  game_name: 'override program',
  game_box_art_url: 'http://lorempixel.com/640/480/sports',
  title: 'Illinois',
  description: 'Id modi animi maiores aut maiores alias.',
  url: 'http://bo.biz',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '06:20:40',
  view_count: 98491,
  created_at: 23,
  streamer_id: 1,
  game_id: 36,
  video_id: 36
},
{
  clip_id: 100,
  user_name: 'Abdul94',
  game_name: 'transmit capacitor',
  game_box_art_url: 'http://lorempixel.com/640/480/food',
  title: 'front-end',
  description: 'Unde impedit nesciunt ad vitae.',
  url: 'http://sallie.net',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '10:31:18',
  view_count: 96533,
  created_at: 75,
  streamer_id: 1,
  game_id: 100,
  video_id: 100
},
{
  clip_id: 61,
  user_name: 'Kaleigh33',
  game_name: 'reboot microchip',
  game_box_art_url: 'http://lorempixel.com/640/480/animals',
  title: 'withdrawal',
  description: 'Enim facilis dolor quo deserunt dolorem.',
  url: 'http://lillian.name',
  thumbnail_url: 'http://lorempixel.com/640/480/sports',
  duration: '06:00:27',
  view_count: 96178,
  created_at: 46,
  streamer_id: 1,
  game_id: 61,
  video_id: 61
},
{
  clip_id: 72,
  user_name: 'Bettie_Boyle17',
  game_name: 'back up matrix',
  game_box_art_url: 'http://lorempixel.com/640/480/sports',
  title: 'Steel',
  description: 'Odit nesciunt ex veritatis tempora quae perspiciatis ad perferendis optio.',
  url: 'https://michaela.name',
  thumbnail_url: 'http://lorempixel.com/640/480/transport',
  duration: '20:04:39',
  view_count: 96161,
  created_at: 53,
  streamer_id: 1,
  game_id: 72,
  video_id: 72
},
{
  clip_id: 67,
  user_name: 'Margret.Hodkiewicz',
  game_name: 'index card',
  game_box_art_url: 'http://lorempixel.com/640/480/fashion',
  title: 'backing up',
  description: 'Debitis pariatur laboriosam non officiis qui velit placeat ut.',
  url: 'http://soledad.com',
  thumbnail_url: 'http://lorempixel.com/640/480/business',
  duration: '04:39:27',
  view_count: 93063,
  created_at: 16,
  streamer_id: 1,
  game_id: 67,
  video_id: 67
},
{
  clip_id: 87,
  user_name: 'Jairo_Gusikowski26',
  game_name: 'input matrix',
  game_box_art_url: 'http://lorempixel.com/640/480/transport',
  title: 'Credit Card Account',
  description: 'Et in non magnam saepe enim veniam accusantium non.',
  url: 'https://audreanne.org',
  thumbnail_url: 'http://lorempixel.com/640/480/business',
  duration: '12:01:08',
  view_count: 88218,
  created_at: 20,
  streamer_id: 1,
  game_id: 87,
  video_id: 87
},
{
  clip_id: 93,
  user_name: 'Carlee.Jakubowski',
  game_name: 'hack interface',
  game_box_art_url: 'http://lorempixel.com/640/480/animals',
  title: 'solid state',
  description: 'Illum reprehenderit error velit hic saepe sit.',
  url: 'https://ryann.net',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '06:10:33',
  view_count: 86837,
  created_at: 94,
  streamer_id: 1,
  game_id: 93,
  video_id: 93
},
{
  clip_id: 11,
  user_name: 'Jerry55',
  game_name: 'calculate transmitter',
  game_box_art_url: 'http://lorempixel.com/640/480/sports',
  title: 'strategize',
  description: 'Id maiores voluptatibus qui voluptatibus.',
  url: 'http://danika.biz',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '07:36:37',
  view_count: 86428,
  created_at: 59,
  streamer_id: 1,
  game_id: 11,
  video_id: 11
},
{
  clip_id: 27,
  user_name: 'Camila.Kuvalis',
  game_name: 'transmit monitor',
  game_box_art_url: 'http://lorempixel.com/640/480/transport',
  title: 'silver',
  description: 'Et quia odio porro dolore non.',
  url: 'https://king.com',
  thumbnail_url: 'http://lorempixel.com/640/480/food',
  duration: '20:56:19',
  view_count: 83383,
  created_at: 70,
  streamer_id: 1,
  game_id: 27,
  video_id: 27
},
{
  clip_id: 24,
  user_name: 'Erik92',
  game_name: 'hack panel',
  game_box_art_url: 'http://lorempixel.com/640/480/food',
  title: 'morph',
  description: 'Quia magni dicta rerum dolore.',
  url: 'https://retha.name',
  thumbnail_url: 'http://lorempixel.com/640/480/business',
  duration: '06:20:44',
  view_count: 83114,
  created_at: 1,
  streamer_id: 1,
  game_id: 24,
  video_id: 24
},
{
  clip_id: 50,
  user_name: 'Pasquale.Lind',
  game_name: 'reboot monitor',
  game_box_art_url: 'http://lorempixel.com/640/480/transport',
  title: 'Quality',
  description: 'Placeat sit fuga ducimus minus ea esse.',
  url: 'http://joaquin.biz',
  thumbnail_url: 'http://lorempixel.com/640/480/cats',
  duration: '18:34:17',
  view_count: 81249,
  created_at: 85,
  streamer_id: 1,
  game_id: 50,
  video_id: 50
},
{
  clip_id: 31,
  user_name: 'Lillie66',
  game_name: 'compress program',
  game_box_art_url: 'http://lorempixel.com/640/480/technics',
  title: 'India',
  description: 'Ipsum officia aliquam sed minus.',
  url: 'http://iva.com',
  thumbnail_url: 'http://lorempixel.com/640/480/transport',
  duration: '05:33:48',
  view_count: 80459,
  created_at: 23,
  streamer_id: 1,
  game_id: 31,
  video_id: 31
},
{
  clip_id: 57,
  user_name: 'Terrill_Schroeder54',
  game_name: 'bypass port',
  game_box_art_url: 'http://lorempixel.com/640/480/food',
  title: 'clicks-and-mortar',
  description: 'Repellendus ea autem dolor repudiandae minus.',
  url: 'https://bianka.biz',
  thumbnail_url: 'http://lorempixel.com/640/480/business',
  duration: '12:53:35',
  view_count: 77875,
  created_at: 33,
  streamer_id: 1,
  game_id: 57,
  video_id: 57
},
{
  clip_id: 69,
  user_name: 'Walker_Wisoky',
  game_name: 'program microchip',
  game_box_art_url: 'http://lorempixel.com/640/480/abstract',
  title: 'Center',
  description: 'Inventore exercitationem eum qui.',
  url: 'https://shanel.name',
  thumbnail_url: 'http://lorempixel.com/640/480/animals',
  duration: '06:18:47',
  view_count: 76007,
  created_at: 6,
  streamer_id: 1,
  game_id: 69,
  video_id: 69
},
{
  clip_id: 70,
  user_name: 'Garrison.Reichert',
  game_name: 'bypass monitor',
  game_box_art_url: 'http://lorempixel.com/640/480/nature',
  title: 'Wooden',
  description: 'Minima reiciendis quisquam dolore nam dignissimos eaque velit unde.',
  url: 'http://lavinia.info',
  thumbnail_url: 'http://lorempixel.com/640/480/business',
  duration: '09:50:19',
  view_count: 75880,
  created_at: 36,
  streamer_id: 1,
  game_id: 70,
  video_id: 70
}]

export { recentBroadcasts, recentHighlights, popularClips };