const recentBroadcasts = [{
  video_id: 56,
  user_name: 'Okey_Buckridge65',
  game_name: 'index port',
  game_box_art_url: 'http://lorempixel.com/640/480/people',
  video_title: 'District Soft',
  video_description: 'Veniam quidem doloremque modi eveniet nihil nulla expedita magnam deserunt.',
  url: 'https://damon.biz',
  thumbnail_url: 'http://lorempixel.com/640/480/abstract',
  duration: '08:14:05',
  view_count: 77615,
  created_at: 2,
  streamer_id: 1,
  game_id: 56
},
{
  video_id: 82,
  user_name: 'Jaclyn_Bosco12',
  game_name: 'parse bus',
  game_box_art_url: 'http://lorempixel.com/640/480/business',
  video_title: 'generate azure',
  video_description: 'A possimus dolor temporibus harum libero fugiat quo quis.',
  url: 'http://cecile.biz',
  thumbnail_url: 'http://lorempixel.com/640/480/animals',
  duration: '11:43:15',
  view_count: 67626,
  created_at: 3,
  streamer_id: 1,
  game_id: 82
},
{
  video_id: 73,
  user_name: 'Curt.Jacobi',
  game_name: 'generate interface',
  game_box_art_url: 'http://lorempixel.com/640/480/animals',
  video_title: 'Ball Flat',
  video_description: 'Vitae consequatur esse molestiae perferendis doloribus iure.',
  url: 'http://valentina.net',
  thumbnail_url: 'http://lorempixel.com/640/480/cats',
  duration: '16:23:32',
  view_count: 51094,
  created_at: 4,
  streamer_id: 1,
  game_id: 73
},
{
  video_id: 79,
  user_name: 'Dorthy_Bruen37',
  game_name: 'program transmitter',
  game_box_art_url: 'http://lorempixel.com/640/480/business',
  video_title: 'invoice Run',
  video_description: 'Rerum aut quae iusto corporis.',
  url: 'http://arvel.com',
  thumbnail_url: 'http://lorempixel.com/640/480/sports',
  duration: '13:11:36',
  view_count: 43823,
  created_at: 4,
  streamer_id: 1,
  game_id: 79
},
{
  video_id: 88,
  user_name: 'Terence92',
  game_name: 'back up card',
  game_box_art_url: 'http://lorempixel.com/640/480/nightlife',
  video_title: 'Refined New Hampshire',
  video_description: 'Ratione eos dolorem vel corrupti recusandae aliquid.',
  url: 'http://warren.org',
  thumbnail_url: 'http://lorempixel.com/640/480/people',
  duration: '06:42:22',
  view_count: 86962,
  created_at: 4,
  streamer_id: 1,
  game_id: 88
},
{
  video_id: 51,
  user_name: 'Jolie.Heaney',
  game_name: 'parse system',
  game_box_art_url: 'http://lorempixel.com/640/480/city',
  video_title: 'Table connect',
  video_description: 'Impedit aspernatur quo velit mollitia sit magnam nemo.',
  url: 'https://alexzander.info',
  thumbnail_url: 'http://lorempixel.com/640/480/people',
  duration: '05:24:13',
  view_count: 91711,
  created_at: 6,
  streamer_id: 1,
  game_id: 51
},
{
  video_id: 75,
  user_name: 'Loren_Stoltenberg83',
  game_name: 'synthesize hard drive',
  game_box_art_url: 'http://lorempixel.com/640/480/sports',
  video_title: 'end-to-end Coordinator',
  video_description: 'Repudiandae magnam voluptatem ipsam autem omnis.',
  url: 'http://glenda.name',
  thumbnail_url: 'http://lorempixel.com/640/480/business',
  duration: '20:40:15',
  view_count: 36773,
  created_at: 6,
  streamer_id: 1,
  game_id: 75
},
{
  video_id: 15,
  user_name: 'Caterina.Beahan35',
  game_name: 'generate pixel',
  game_box_art_url: 'http://lorempixel.com/640/480/cats',
  video_title: 'bandwidth users',
  video_description: 'Quisquam dolorem natus tempora quidem quae.',
  url: 'https://brandyn.net',
  thumbnail_url: 'http://lorempixel.com/640/480/nature',
  duration: '07:51:38',
  view_count: 71016,
  created_at: 6,
  streamer_id: 1,
  game_id: 15
},
{
  video_id: 9,
  user_name: 'Ismael89',
  game_name: 'generate port',
  game_box_art_url: 'http://lorempixel.com/640/480/people',
  video_title: 'object-oriented Identity',
  video_description: 'Repellendus aspernatur minima dolore.',
  url: 'http://makenna.net',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '05:11:31',
  view_count: 10531,
  created_at: 7,
  streamer_id: 1,
  game_id: 9
},
{
  video_id: 64,
  user_name: 'Keshaun80',
  game_name: 'hack array',
  game_box_art_url: 'http://lorempixel.com/640/480/animals',
  video_title: 'Arizona encoding',
  video_description: 'Deserunt vel accusamus consequatur.',
  url: 'http://devin.name',
  thumbnail_url: 'http://lorempixel.com/640/480/fashion',
  duration: '00:16:52',
  view_count: 64599,
  created_at: 7,
  streamer_id: 1,
  game_id: 64
},
{
  video_id: 72,
  user_name: 'Cicero_Greenfelder11',
  game_name: 'hack system',
  game_box_art_url: 'http://lorempixel.com/640/480/business',
  video_title: 'Business-focused Hryvnia',
  video_description: 'Et voluptatibus maiores et voluptatem.',
  url: 'http://dax.org',
  thumbnail_url: 'http://lorempixel.com/640/480/business',
  duration: '06:19:19',
  view_count: 68278,
  created_at: 7,
  streamer_id: 1,
  game_id: 72
},
{
  video_id: 100,
  user_name: 'Raymundo_Goyette14',
  game_name: 'connect panel',
  game_box_art_url: 'http://lorempixel.com/640/480/technics',
  video_title: 'deposit Upgradable',
  video_description: 'Sint ut sapiente expedita amet accusamus nobis qui dolore accusantium.',
  url: 'https://derrick.org',
  thumbnail_url: 'http://lorempixel.com/640/480/nightlife',
  duration: '22:49:04',
  view_count: 1882,
  created_at: 8,
  streamer_id: 1,
  game_id: 100
},
{
  video_id: 59,
  user_name: 'Rhoda35',
  game_name: 'transmit monitor',
  game_box_art_url: 'http://lorempixel.com/640/480/food',
  video_title: 'Berkshire Metrics',
  video_description: 'Ipsa accusamus numquam sunt.',
  url: 'http://camila.com',
  thumbnail_url: 'http://lorempixel.com/640/480/nature',
  duration: '22:09:33',
  view_count: 99128,
  created_at: 8,
  streamer_id: 1,
  game_id: 59
},
{
  video_id: 31,
  user_name: 'Dominique85',
  game_name: 'navigate hard drive',
  game_box_art_url: 'http://lorempixel.com/640/480/transport',
  video_title: 'Grass-roots Pike',
  video_description: 'Repellat dolor sit at asperiores.',
  url: 'http://axel.info',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '20:27:01',
  view_count: 99581,
  created_at: 12,
  streamer_id: 1,
  game_id: 31
},
{
  video_id: 83,
  user_name: 'Xzavier15',
  game_name: 'input alarm',
  game_box_art_url: 'http://lorempixel.com/640/480/abstract',
  video_title: 'Grocery Garden',
  video_description: 'Vel est earum autem iste.',
  url: 'https://eve.name',
  thumbnail_url: 'http://lorempixel.com/640/480/nightlife',
  duration: '13:41:34',
  view_count: 74258,
  created_at: 17,
  streamer_id: 1,
  game_id: 83
}]

const recentHighlights = [{
  video_id: 31,
  user_name: 'Dominique85',
  game_name: 'navigate hard drive',
  game_box_art_url: 'http://lorempixel.com/640/480/transport',
  video_title: 'Grass-roots Pike',
  video_description: 'Repellat dolor sit at asperiores.',
  url: 'http://axel.info',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '20:27:01',
  view_count: 99581,
  created_at: 12,
  streamer_id: 1,
  game_id: 31
},
{
  video_id: 59,
  user_name: 'Rhoda35',
  game_name: 'transmit monitor',
  game_box_art_url: 'http://lorempixel.com/640/480/food',
  video_title: 'Berkshire Metrics',
  video_description: 'Ipsa accusamus numquam sunt.',
  url: 'http://camila.com',
  thumbnail_url: 'http://lorempixel.com/640/480/nature',
  duration: '22:09:33',
  view_count: 99128,
  created_at: 8,
  streamer_id: 1,
  game_id: 59
},
{
  video_id: 94,
  user_name: 'Maude23',
  game_name: 'program transmitter',
  game_box_art_url: 'http://lorempixel.com/640/480/city',
  video_title: 'open-source Tasty',
  video_description: 'Architecto vitae illum.',
  url: 'https://bernie.org',
  thumbnail_url: 'http://lorempixel.com/640/480/nature',
  duration: '20:31:44',
  view_count: 98805,
  created_at: 39,
  streamer_id: 1,
  game_id: 94
},
{
  video_id: 68,
  user_name: 'Jaydon87',
  game_name: 'compress panel',
  game_box_art_url: 'http://lorempixel.com/640/480/sports',
  video_title: 'Prairie Principal',
  video_description: 'Neque enim nihil natus repudiandae.',
  url: 'https://jack.info',
  thumbnail_url: 'http://lorempixel.com/640/480/animals',
  duration: '08:04:51',
  view_count: 96424,
  created_at: 30,
  streamer_id: 1,
  game_id: 68
},
{
  video_id: 32,
  user_name: 'Amira.Davis90',
  game_name: 'reboot interface',
  game_box_art_url: 'http://lorempixel.com/640/480/food',
  video_title: 'customized New Mexico',
  video_description: 'Pariatur beatae magnam iste ut explicabo quis rerum.',
  url: 'http://llewellyn.net',
  thumbnail_url: 'http://lorempixel.com/640/480/animals',
  duration: '15:37:34',
  view_count: 95815,
  created_at: 37,
  streamer_id: 1,
  game_id: 32
},
{
  video_id: 20,
  user_name: 'Raymundo_Greenholt',
  game_name: 'reboot alarm',
  game_box_art_url: 'http://lorempixel.com/640/480/sports',
  video_title: 'process improvement Triple-buffered',
  video_description: 'Voluptates qui explicabo.',
  url: 'http://adriana.net',
  thumbnail_url: 'http://lorempixel.com/640/480/food',
  duration: '21:07:38',
  view_count: 95045,
  created_at: 47,
  streamer_id: 1,
  game_id: 20
},
{
  video_id: 51,
  user_name: 'Jolie.Heaney',
  game_name: 'parse system',
  game_box_art_url: 'http://lorempixel.com/640/480/city',
  video_title: 'Table connect',
  video_description: 'Impedit aspernatur quo velit mollitia sit magnam nemo.',
  url: 'https://alexzander.info',
  thumbnail_url: 'http://lorempixel.com/640/480/people',
  duration: '05:24:13',
  view_count: 91711,
  created_at: 6,
  streamer_id: 1,
  game_id: 51
},
{
  video_id: 3,
  user_name: 'Robb.Steuber',
  game_name: 'back up array',
  game_box_art_url: 'http://lorempixel.com/640/480/people',
  video_title: 'plum Handcrafted',
  video_description: 'Delectus dolores sint omnis ea ut saepe corporis.',
  url: 'http://tanya.name',
  thumbnail_url: 'http://lorempixel.com/640/480/nature',
  duration: '07:00:24',
  view_count: 89636,
  created_at: 41,
  streamer_id: 1,
  game_id: 3
},
{
  video_id: 88,
  user_name: 'Terence92',
  game_name: 'back up card',
  game_box_art_url: 'http://lorempixel.com/640/480/nightlife',
  video_title: 'Refined New Hampshire',
  video_description: 'Ratione eos dolorem vel corrupti recusandae aliquid.',
  url: 'http://warren.org',
  thumbnail_url: 'http://lorempixel.com/640/480/people',
  duration: '06:42:22',
  view_count: 86962,
  created_at: 4,
  streamer_id: 1,
  game_id: 88
},
{
  video_id: 41,
  user_name: 'Holly.Block2',
  game_name: 'transmit panel',
  game_box_art_url: 'http://lorempixel.com/640/480/nightlife',
  video_title: 'users Cambridgeshire',
  video_description: 'Et voluptate ut ut est voluptatem adipisci.',
  url: 'https://titus.org',
  thumbnail_url: 'http://lorempixel.com/640/480/sports',
  duration: '02:28:22',
  view_count: 86937,
  created_at: 46,
  streamer_id: 1,
  game_id: 41
},
{
  video_id: 13,
  user_name: 'Brycen.Schneider',
  game_name: 'transmit card',
  game_box_art_url: 'http://lorempixel.com/640/480/nature',
  video_title: 'schemas bi-directional',
  video_description: 'Et ex omnis qui blanditiis.',
  url: 'http://rahsaan.com',
  thumbnail_url: 'http://lorempixel.com/640/480/city',
  duration: '00:11:23',
  view_count: 86556,
  created_at: 35,
  streamer_id: 1,
  game_id: 13
},
{
  video_id: 91,
  user_name: 'Nola_Olson40',
  game_name: 'index firewall',
  game_box_art_url: 'http://lorempixel.com/640/480/technics',
  video_title: 'Timor-Leste Trace',
  video_description: 'Sunt nulla voluptatem quia totam cupiditate molestiae deleniti eligendi.',
  url: 'http://justen.com',
  thumbnail_url: 'http://lorempixel.com/640/480/people',
  duration: '14:40:49',
  view_count: 84271,
  created_at: 33,
  streamer_id: 1,
  game_id: 91
},
{
  video_id: 45,
  user_name: 'Brant.Lind',
  game_name: 'program circuit',
  game_box_art_url: 'http://lorempixel.com/640/480/nature',
  video_title: 'Intelligent Graphical User Interface',
  video_description: 'Alias voluptas debitis qui enim corrupti inventore quasi.',
  url: 'http://troy.info',
  thumbnail_url: 'http://lorempixel.com/640/480/business',
  duration: '20:40:48',
  view_count: 81888,
  created_at: 24,
  streamer_id: 1,
  game_id: 45
},
{
  video_id: 43,
  user_name: 'Dawn.Torphy',
  game_name: 'quantify microchip',
  game_box_art_url: 'http://lorempixel.com/640/480/sports',
  video_title: 'redundant multi-byte',
  video_description: 'Sint officia in voluptatem repellat.',
  url: 'https://moises.net',
  thumbnail_url: 'http://lorempixel.com/640/480/animals',
  duration: '12:58:12',
  view_count: 79305,
  created_at: 18,
  streamer_id: 1,
  game_id: 43
},
{
  video_id: 56,
  user_name: 'Okey_Buckridge65',
  game_name: 'index port',
  game_box_art_url: 'http://lorempixel.com/640/480/people',
  video_title: 'District Soft',
  video_description: 'Veniam quidem doloremque modi eveniet nihil nulla expedita magnam deserunt.',
  url: 'https://damon.biz',
  thumbnail_url: 'http://lorempixel.com/640/480/abstract',
  duration: '08:14:05',
  view_count: 77615,
  created_at: 2,
  streamer_id: 1,
  game_id: 56
}]

const popularClips = [{
  clip_id: 37,
  user_name: 'Jeromy_Fay',
  game_name: 'bypass system',
  game_box_art_url: 'http://lorempixel.com/640/480/nightlife',
  clip_title: 'Reverse-engineered',
  clip_description: 'At rem consequuntur aut ratione.',
  url: 'http://nya.net',
  thumbnail_url: 'http://lorempixel.com/640/480/business',
  duration: '17:20:50',
  view_count: 99603,
  created_at: 39,
  streamer_id: 1,
  game_id: 37,
  video_id: 37
},
{
  clip_id: 1,
  user_name: 'Adaline.Beatty65',
  game_name: 'calculate bandwidth',
  game_box_art_url: 'http://lorempixel.com/640/480/transport',
  clip_title: 'calculate',
  clip_description: 'Qui quo consequuntur est.',
  url: 'https://conrad.net',
  thumbnail_url: 'http://lorempixel.com/640/480/transport',
  duration: '05:14:13',
  view_count: 98921,
  created_at: 74,
  streamer_id: 1,
  game_id: 1,
  video_id: 1
},
{
  clip_id: 85,
  user_name: 'Cassandre_Kessler58',
  game_name: 'reboot pixel',
  game_box_art_url: 'http://lorempixel.com/640/480/animals',
  clip_title: 'withdrawal',
  clip_description: 'Repudiandae voluptatibus commodi.',
  url: 'http://chadrick.info',
  thumbnail_url: 'http://lorempixel.com/640/480/business',
  duration: '07:47:12',
  view_count: 98905,
  created_at: 39,
  streamer_id: 1,
  game_id: 85,
  video_id: 85
},
{
  clip_id: 76,
  user_name: 'Shawn9',
  game_name: 'calculate transmitter',
  game_box_art_url: 'http://lorempixel.com/640/480/people',
  clip_title: 'cross-platform',
  clip_description: 'Cumque exercitationem nobis et officia delectus corporis delectus.',
  url: 'http://tabitha.name',
  thumbnail_url: 'http://lorempixel.com/640/480/cats',
  duration: '21:00:52',
  view_count: 94698,
  created_at: 28,
  streamer_id: 1,
  game_id: 76,
  video_id: 76
},
{
  clip_id: 25,
  user_name: 'Sandrine_Franecki2',
  game_name: 'compress system',
  game_box_art_url: 'http://lorempixel.com/640/480/food',
  clip_title: 'interactive',
  clip_description: 'Reiciendis ea voluptatem vel ipsum.',
  url: 'http://alice.info',
  thumbnail_url: 'http://lorempixel.com/640/480/nightlife',
  duration: '16:14:13',
  view_count: 94621,
  created_at: 36,
  streamer_id: 1,
  game_id: 25,
  video_id: 25
},
{
  clip_id: 60,
  user_name: 'Titus_Krajcik93',
  game_name: 'transmit pixel',
  game_box_art_url: 'http://lorempixel.com/640/480/technics',
  clip_title: 'programming',
  clip_description: 'Quidem qui architecto aperiam qui minus officiis et voluptas.',
  url: 'https://efren.net',
  thumbnail_url: 'http://lorempixel.com/640/480/transport',
  duration: '12:30:26',
  view_count: 92526,
  created_at: 100,
  streamer_id: 1,
  game_id: 60,
  video_id: 60
},
{
  clip_id: 83,
  user_name: 'Seamus_Kunze',
  game_name: 'synthesize sensor',
  game_box_art_url: 'http://lorempixel.com/640/480/food',
  clip_title: 'program',
  clip_description: 'Dolor qui optio voluptas inventore perferendis fugiat ut quam.',
  url: 'http://matilde.org',
  thumbnail_url: 'http://lorempixel.com/640/480/nightlife',
  duration: '05:00:54',
  view_count: 91373,
  created_at: 81,
  streamer_id: 1,
  game_id: 83,
  video_id: 83
},
{
  clip_id: 54,
  user_name: 'Kaitlin21',
  game_name: 'program array',
  game_box_art_url: 'http://lorempixel.com/640/480/technics',
  clip_title: 'Representative',
  clip_description: 'Libero aliquam et iure.',
  url: 'http://rhoda.name',
  thumbnail_url: 'http://lorempixel.com/640/480/abstract',
  duration: '07:43:12',
  view_count: 90827,
  created_at: 79,
  streamer_id: 1,
  game_id: 54,
  video_id: 54
},
{
  clip_id: 32,
  user_name: 'Odell.Monahan37',
  game_name: 'navigate interface',
  game_box_art_url: 'http://lorempixel.com/640/480/nature',
  clip_title: 'matrix',
  clip_description: 'Aut quia fuga.',
  url: 'https://elroy.name',
  thumbnail_url: 'http://lorempixel.com/640/480/animals',
  duration: '02:46:21',
  view_count: 90160,
  created_at: 71,
  streamer_id: 1,
  game_id: 32,
  video_id: 32
},
{
  clip_id: 14,
  user_name: 'Ignacio_Lehner',
  game_name: 'calculate feed',
  game_box_art_url: 'http://lorempixel.com/640/480/sports',
  clip_title: 'Sleek Granite Chicken',
  clip_description: 'Eum culpa dicta necessitatibus doloribus ea aut magnam nihil.',
  url: 'http://sarina.org',
  thumbnail_url: 'http://lorempixel.com/640/480/technics',
  duration: '10:29:46',
  view_count: 89585,
  created_at: 65,
  streamer_id: 1,
  game_id: 14,
  video_id: 14
},
{
  clip_id: 86,
  user_name: 'Everette_Jacobi30',
  game_name: 'program microchip',
  game_box_art_url: 'http://lorempixel.com/640/480/city',
  clip_title: 'Computers',
  clip_description: 'Aliquam aut natus.',
  url: 'http://rosemary.name',
  thumbnail_url: 'http://lorempixel.com/640/480/nightlife',
  duration: '18:16:51',
  view_count: 89553,
  created_at: 9,
  streamer_id: 1,
  game_id: 86,
  video_id: 86
},
{
  clip_id: 62,
  user_name: 'Gabrielle57',
  game_name: 'program bus',
  game_box_art_url: 'http://lorempixel.com/640/480/technics',
  clip_title: 'maroon',
  clip_description: 'Nulla voluptatum omnis asperiores nulla dolorum laudantium libero.',
  url: 'https://alvis.org',
  thumbnail_url: 'http://lorempixel.com/640/480/nightlife',
  duration: '06:31:30',
  view_count: 89420,
  created_at: 15,
  streamer_id: 1,
  game_id: 62,
  video_id: 62
},
{
  clip_id: 53,
  user_name: 'Nicole_Lang',
  game_name: 'generate matrix',
  game_box_art_url: 'http://lorempixel.com/640/480/abstract',
  clip_title: 'synergize',
  clip_description: 'Et hic explicabo.',
  url: 'http://fabian.net',
  thumbnail_url: 'http://lorempixel.com/640/480/animals',
  duration: '23:59:56',
  view_count: 87846,
  created_at: 6,
  streamer_id: 1,
  game_id: 53,
  video_id: 53
},
{
  clip_id: 74,
  user_name: 'Kendrick75',
  game_name: 'transmit card',
  game_box_art_url: 'http://lorempixel.com/640/480/fashion',
  clip_title: 'Buckinghamshire',
  clip_description: 'Omnis molestiae a.',
  url: 'http://gerry.org',
  thumbnail_url: 'http://lorempixel.com/640/480/animals',
  duration: '18:22:51',
  view_count: 87085,
  created_at: 9,
  streamer_id: 1,
  game_id: 74,
  video_id: 74
},
{
  clip_id: 77,
  user_name: 'Angela.Cormier59',
  game_name: 'synthesize card',
  game_box_art_url: 'http://lorempixel.com/640/480/nature',
  clip_title: 'invoice',
  clip_description: 'Non et qui voluptas perferendis et.',
  url: 'https://darrick.biz',
  thumbnail_url: 'http://lorempixel.com/640/480/abstract',
  duration: '02:20:48',
  view_count: 82626,
  created_at: 52,
  streamer_id: 1,
  game_id: 77,
  video_id: 77
}]

export { recentBroadcasts, recentHighlights, popularClips };